# Rustfmt configuration file

# Basic styling
max_width = 100
tab_spaces = 4
edition = "2024"
newline_style = "Unix"

# Formatting options
fn_args_layout = "Tall"
use_try_shorthand = true
use_field_init_shorthand = true
reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"

# Comments and documentation
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true

# Indentation and blocks
match_arm_blocks = true
match_block_trailing_comma = false
trailing_semicolon = true
trailing_comma = "Vertical"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true

# Error handling
error_on_line_overflow = true
error_on_unformatted = false

# Additional tidying
merge_derives = true
use_small_heuristics = "Default"